[project]
name = "agent-aixperts-grosse-conf-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "colorlog>=6.10.1",
    "google-cloud-aiplatform>=1.38",
    "openpyxl>=3.1.5",
    "pydantic-ai>=0.0.15",
    "pydantic-settings>=2.0.0",
    "streamlit>=1.52.2",
]
